
# Open this file in vscode and use it with the rest-client plugin

# Open this file in vscode and use it with the rest-client plugin

POST http://<://<url-to-your-aci-endpoint>/score HTTP/1.1
Content-Type: application/json
Authorization: Bearer <your-api-key-goes-here>

{
    "data": [{'A1Cresult': 'None',
 'admission_source_id': 'Emergency Room',
 'admission_type_id': 'Emergency',
 'age': '0-20',
 'change': 'Ch',
 'diabetesMed': 'Yes',
 'diag_1': 0,
 'discharge_disposition_id': 'Home',
 'gender': 'Female',
 'insulin': 'Up',
 'max_glu_serum': 'None',
 'num_lab_procedures': 59,
 'num_medications': 18,
 'num_procedures': 0,
 'number_diagnoses': 9,
 'number_emergency': 0,
 'number_inpatient': 0,
 'number_outpatient': 0,
 'race': 'Caucasian',
 'time_in_hospital': 3}]
}